apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-frontapp
  namespace: {{ .Values.namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.selector.app }}
  template:
    metadata:
      labels:
        app: {{ .Values.selector.app }}
    spec:
      serviceAccountName: front
      containers:
        - name: python-container
          image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 3000
          env:
            {{- toYaml .Values.env | nindent 12 }}
