apiVersion: secrets-store.csi.x-k8s.io/v1  # Specifies the API version for the Secrets Store CSI driver
kind: SecretProviderClass                  # Defines a custom resource of type SecretProviderClass, used by the CSI driver
metadata:
  name: test-csi-class                     # Name of the SecretProviderClass, unique within the namespace
  namespace: namespace      
spec:
  parameters:
    objects: |                             # Defines the objects (secrets) to be fetched from the secret store
      - objectName: "secret-test"  # Logical name of the secret object that will be used within the application
        secretPath: "kv-1/path/to/secret"         # Path in Vault where the secret is stored
        secretKey: "secret-key"             # The specific key of the secret within the secret path
    roleName: pod-role                  # The Vault role name that the pod will use to authenticate to fetch secrets
    vaultAddress: http://vault-ip:port  # Address of the Vault instance
    vaultAuthMountPath: kubernetes-dev     # Vault auth path used for Kubernetes authentication (usually set in Vault's configuration)
  provider: vault                          # Specifies that Vault is the secret provider for this SecretProviderClass
  secretObjects:                           # Maps the fetched secrets into Kubernetes secrets
    - secretName: secret-name        # Name of the Kubernetes secret that will be created from the Vault secrets
      type: Opaque                         # Type of the Kubernetes secret (Opaque is used for general-purpose secrets)
      data:                                # List of data keys that will be populated in the Kubernetes secret
        - key: secret-test  # Key in the Kubernetes secret where the value will be stored
          objectName: secret-test  # Maps the fetched Vault object (secret) to this Kubernetes secret key
